name: Feature Request
description: Suggest a new feature or enhancement for Verge CLI
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What are you trying to accomplish? Describe the problem or workflow this feature would address.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this to work. Include example commands or output if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or screenshots that might help.
    validations:
      required: false
